export const SearchActionTypes = {
  SEARCH_MOVIE: "SEARCH_MOVIE",
  SEARCH_MOVIE_SUCCESS: "SEARCH_MOVIE_SUCCESS",
  SEARCH_MOVIE_LOADING: "SEARCH_MOVIE_LOADING",
  SEARCH_MOVIE_FAILURE: "SEARCH_MOVIE_FAILURE",
  SEARCH_MOVIE_RESET: "SEARCH_MOVIE_RESET",
};
