export const MovieActionTypes = {
  GET_NOW_PLAYING_MOVIES: "GET_NOW_PLAYING_MOVIES",
  GET_NOW_PLAYING_MOVIES_SUCCESS: "GET_NOW_PLAYING_MOVIES_SUCCESS",
  GET_NOW_PLAYING_MOVIES_LOADING: "GET_NOW_PLAYING_MOVIES_LOADING",
  GET_NOW_PLAYING_MOVIES_FAILURE: "GET_NOW_PLAYING_MOVIES_FAILURE",

  GET_POPULAR_MOVIES: "GET_POPULAR_MOVIES",
  GET_POPULAR_MOVIES_SUCCESS: "GET_POPULAR_MOVIES_SUCCESS",
  GET_POPULAR_MOVIES_LOADING: "GET_POPULAR_MOVIES_LOADING",
  GET_POPULAR_MOVIES_FAILURE: "GET_POPULAR_MOVIES_FAILURE",

  GET_TOP_RATED_MOVIES: "GET_TOP_RATED_MOVIES",
  GET_TOP_RATED_MOVIES_SUCCESS: "GET_TOP_RATED_MOVIES_SUCCESS",
  GET_TOP_RATED_MOVIES_LOADING: "GET_TOP_RATED_MOVIES_LOADING",
  GET_TOP_RATED_MOVIES_FAILURE: "GET_TOP_RATED_MOVIES_FAILURE",

  GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
  GET_UPCOMING_MOVIES_SUCCESS: "GET_UPCOMING_MOVIES_SUCCESS",
  GET_UPCOMING_MOVIES_LOADING: "GET_UPCOMING_MOVIES_LOADING",
  GET_UPCOMING_MOVIES_FAILURE: "GET_UPCOMING_MOVIES_FAILURE",

  GET_TRAILER_MOVIE: "GET_TRAILER_MOVIE",
  GET_TRAILER_MOVIE_SUCCESS: "GET_TRAILER_MOVIE_SUCCESS",
  GET_TRAILER_MOVIE_LOADING: "GET_TRAILER_MOVIE_LOADING",
  GET_TRAILER_MOVIE_FAILURE: "GET_TRAILER_MOVIE_FAILURE",

  SET_TOGGLE: "SET_TOGGLE",
  SET_OPEN: "SET_OPEN",
  SET_ID: "SET_ID",
};
