export const products = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_LOADING: "GET_PRODUCTS_LOADING",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  GET_PRODUCTS_RESET: "GET_PRODUCTS_RESET",

  GET_SUB_GROUPS: "GET_SUB_GROUPS",
  GET_SUB_GROUPS_SUCCESS: "GET_SUB_GROUPS_SUCCESS",
  GET_SUB_GROUPS_LOADING: "GET_SUB_GROUPS_LOADING",
  GET_SUB_GROUPS_FAILURE: "GET_SUB_GROUPS_FAILURE",
  GET_SUB_GROUPS_RESET: "GET_SUB_GROUPS_RESET",

  TAB_CHANGE: "TAB_CHANGE",
  TAB_CHANGE_SUCCESS: "TAB_CHANGE_SUCCESS",
  TAB_CHANGE_LOADING: "TAB_CHANGE_LOADING",
  TAB_CHANGE_FAILURE: "TAB_CHANGE_FAILURE",
  TAB_CHANGE_RESET: "TAB_CHANGE_RESET",

  ADD_DRAFT_PRODUCT: "ADD_DRAFT_PRODUCT",
  ADD_DRAFT_PRODUCT_SUCCESS: "ADD_DRAFT_PRODUCT_SUCCESS",
  ADD_DRAFT_PRODUCT_LOADING: "ADD_DRAFT_PRODUCT_LOADING",
  ADD_DRAFT_PRODUCT_FAILURE: "ADD_DRAFT_PRODUCT_FAILURE",
  ADD_DRAFT_PRODUCT_RESET: "ADD_DRAFT_PRODUCT_RESET",

  FILTER_SET: "FILTER_SET",
  FILTER_SET_SUCCESS: "FILTER_SET_SUCCESS",
  FILTER_SET_LOADING: "FILTER_SET_LOADING",
  FILTER_SET_FAILURE: "FILTER_SET_FAILURE",
  FILTER_SET_RESET: "FILTER_SET_RESET",

  GET_PRODUCT_GROUPS_FROM_ACTIVITIES: "GET_PRODUCT_GROUPS_FROM_ACTIVITIES",
  GET_PRODUCT_GROUPS_FROM_ACTIVITIES_SUCCESS:
    "GET_PRODUCT_GROUPS_FROM_ACTIVITIES_SUCCESS",
  GET_PRODUCT_GROUPS_FROM_ACTIVITIES_LOADING:
    "GET_PRODUCT_GROUPS_FROM_ACTIVITIES_LOADING",
  GET_PRODUCT_GROUPS_FROM_ACTIVITIES_FAILURE:
    "GET_PRODUCT_GROUPS_FROM_ACTIVITIES_FAILURE",
  GET_PRODUCT_GROUPS_FROM_ACTIVITIES_RESET:
    "GET_PRODUCT_GROUPS_FROM_ACTIVITIES_RESET",

  FILTERS_DROPDOWN_VALUES: "FILTERS_DROPDOWN_VALUES",
  FILTERS_DROPDOWN_VALUES_SUCCESS: "FILTERS_DROPDOWN_VALUES_SUCCESS",
  FILTERS_DROPDOWN_VALUES_LOADING: "FILTERS_DROPDOWN_VALUES_LOADING",
  FILTERS_DROPDOWN_VALUES_FAILURE: "FILTERS_DROPDOWN_VALUES_FAILURE",
  FILTERS_DROPDOWN_VALUES_RESET: "FILTERS_DROPDOWN_VALUES_RESET",

  GET_SUB_GROUPS_FROM_GROUPS: "GET_SUB_GROUPS_FROM_GROUPS",
  GET_SUB_GROUPS_FROM_GROUPS_SUCCESS: "GET_SUB_GROUPS_FROM_GROUPS_SUCCESS",
  GET_SUB_GROUPS_FROM_GROUPS_LOADING: "GET_SUB_GROUPS_FROM_GROUPS_LOADING",
  GET_SUB_GROUPS_FROM_GROUPS_FAILURE: "GET_SUB_GROUPS_FROM_GROUPS_FAILURE",
  GET_SUB_GROUPS_FROM_GROUPS_RESET: "GET_SUB_GROUPS_FROM_GROUPS_RESET",

  GET_FIELDS_FROM_SUB_GROUPS: "GET_FIELDS_FROM_SUB_GROUPS",
  GET_FIELDS_FROM_SUB_GROUPS_SUCCESS: "GET_FIELDS_FROM_SUB_GROUPS_SUCCESS",
  GET_FIELDS_FROM_SUB_GROUPS_LOADING: "GET_FIELDS_FROM_SUB_GROUPS_LOADING",
  GET_FIELDS_FROM_SUB_GROUPS_FAILURE: "GET_FIELDS_FROM_SUB_GROUPS_FAILURE",
  GET_FIELDS_FROM_SUB_GROUPS_RESET: "GET_FIELDS_FROM_SUB_GROUPS_RESET",

  ADD_DRAFT_PRICE_ZONE: "ADD_DRAFT_PRICE_ZONE",
  ADD_DRAFT_PRICE_ZONE_SUCCESS: "ADD_DRAFT_PRICE_ZONE_SUCCESS",
  ADD_DRAFT_PRICE_ZONE_LOADING: "ADD_DRAFT_PRICE_ZONE_LOADING",
  ADD_DRAFT_PRICE_ZONE_FAILURE: "ADD_DRAFT_PRICE_ZONE_FAILURE",
  ADD_DRAFT_PRICE_ZONE_RESET: "ADD_DRAFT_PRICE_ZONE_RESET",

  GET_PRICE_ZONE_LIST: "GET_PRICE_ZONE_LIST",
  GET_PRICE_ZONE_LIST_SUCCESS: "GET_PRICE_ZONE_LIST_SUCCESS",
  GET_PRICE_ZONE_LIST_LOADING: "GET_PRICE_ZONE_LIST_LOADING",
  GET_PRICE_ZONE_LIST_FAILURE: "GET_PRICE_ZONE_LIST_FAILURE",
  GET_PRICE_ZONE_LIST_RESET: "GET_PRICE_ZONE_LIST_RESET",

  GET_ADD_PRICE_ZONE_VALUES: "GET_ADD_PRICE_ZONE_VALUES",
  GET_ADD_PRICE_ZONE_VALUES_SUCCESS: "GET_ADD_PRICE_ZONE_VALUES_SUCCESS",
  GET_ADD_PRICE_ZONE_VALUES_LOADING: "GET_ADD_PRICE_ZONE_VALUES_LOADING",
  GET_ADD_PRICE_ZONE_VALUES_FAILURE: "GET_ADD_PRICE_ZONE_VALUES_FAILURE",
  GET_ADD_PRICE_ZONE_VALUES_RESET: "GET_ADD_PRICE_ZONE_VALUES_RESET",

  GET_MASTER_PRICE_ZONE: "GET_MASTER_PRICE_ZONE",
  GET_MASTER_PRICE_ZONE_SUCCESS: "GET_MASTER_PRICE_ZONE_SUCCESS",
  GET_MASTER_PRICE_ZONE_LOADING: "GET_MASTER_PRICE_ZONE_LOADING",
  GET_MASTER_PRICE_ZONE_FAILURE: "GET_MASTER_PRICE_ZONE_FAILURE",
  GET_MASTER_PRICE_ZONE_RESET: "GET_MASTER_PRICE_ZONE_RESET",

  GET_MASTER_PRICE_ZONE_FILTER: "GET_MASTER_PRICE_ZONE_FILTER",
  GET_MASTER_PRICE_ZONE_FILTER_SUCCESS: "GET_MASTER_PRICE_ZONE_FILTER_SUCCESS",
  GET_MASTER_PRICE_ZONE_FILTER_LOADING: "GET_MASTER_PRICE_ZONE_FILTER_LOADING",
  GET_MASTER_PRICE_ZONE_FILTER_FAILURE: "GET_MASTER_PRICE_ZONE_FILTER_FAILURE",
  GET_MASTER_PRICE_ZONE_FILTER_RESET: "GET_MASTER_PRICE_ZONE_FILTER_RESET",

  GET_EXPORT_LIST_LINK: "GET_EXPORT_LIST_LINK",
  GET_EXPORT_LIST_LINK_SUCCESS: "GET_EXPORT_LIST_LINK_SUCCESS",
  GET_EXPORT_LIST_LINK_LOADING: "GET_EXPORT_LIST_LINK_LOADING",
  GET_EXPORT_LIST_LINK_FAILURE: "GET_EXPORT_LIST_LINK_FAILURE",
  GET_EXPORT_LIST_LINK_RESET: "GET_EXPORT_LIST_LINK_RESET",

  EDIT_MASTER_AND_ASSIGN_EXPORT: "EDIT_MASTER_AND_ASSIGN_EXPORT",
  EDIT_MASTER_AND_ASSIGN_EXPORT_SUCCESS:
    "EDIT_MASTER_AND_ASSIGN_EXPORT_SUCCESS",
  EDIT_MASTER_AND_ASSIGN_EXPORT_LOADING:
    "EDIT_MASTER_AND_ASSIGN_EXPORT_LOADING",
  EDIT_MASTER_AND_ASSIGN_EXPORT_FAILURE:
    "EDIT_MASTER_AND_ASSIGN_EXPORT_FAILURE",
  EDIT_MASTER_AND_ASSIGN_EXPORT_RESET: "EDIT_MASTER_AND_ASSIGN_EXPORT_RESET",
};
