export const AuthActionTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_LOADING: "LOGIN_USER_LOADING",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  LOGIN_USER_RESET: "LOGIN_USER_RESET",

  LOGOUT_USER: "LOGOUT_USER",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_LOADING: "LOGOUT_USER_LOADING",
  LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",
  LOGOUT_USER_RESET: "LOGOUT_USER_RESET",

  SIGNUP_USER: "SIGNUP_USER",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
  SIGNUP_USER_LOADING: "SIGNUP_USER_LOADING",
  SIGNUP_USER_FAILURE: "SIGNUP_USER_FAILURE",
  SIGNUP_USER_RESET: "SIGNUP_USER_RESET",
};
